markdown: rdiscount
baseurl: /FiveMoreTopics
permalink: /classes/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Five More Topics
url: https://bsalinas.github.io/FiveMoreTopics
description: Course Materials for Five More Topics.
twitter: bensalinas
